---
title: "mNET-seq analysis for `r paste0(proj)`"
author: "Benjamin Erickson"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
    toc:            true
    toc_float:      true
    toc_depth:      3
    df_print:       "paged"
    code_folding:   "hide"
    self_contained: true
    theme:          "cosmo"
    highlight:      "tango"

---

```{r "chunk opts"}

# Set default chunk options
knitr::opts_chunk$set(
  message    = FALSE, 
  warning    = FALSE,
  comment    = "",
  echo       = FALSE,
  dpi        = 150,
  cache      = FALSE,
  cache.lazy = FALSE
)

```

```{r "plotting parameters", include = FALSE}

# Set plotting parameters
# ymls=here::here("samples.yaml")
ymls <- here::here(ymls)
plot_grpss   <- yaml::read_yaml(ymls)
# proj="test_pipeline"
#res_dir="test_pipeline"
template_dir="src/Rmds"

knitr::knit(here::here(template_dir, "setup.Rmd"), "")

```

# Plot Preview

`r knitr::knit_child(here(template_dir, "heatmap-template.Rmd"))`

# Session info

```{r, echo = FALSE}

sessionInfo()

```


