
```{r "Packages", include = FALSE, cache = FALSE}

# Load packages
library(kableExtra)
library(tidyverse)
library(yaml)
library(cowplot)
library(png)
library(grid)
library(gridExtra)

# Read functions
source(here::here(template_dir, "funs.R"))

```

```{r "Theme", cache = FALSE}

txt_mplyr <- 1.5
ttl_pt <- 10 * txt_mplyr
txt_pt <- 8  * txt_mplyr
ln_pt  <- 0.5

theme_info <- theme_cowplot() +
  theme(
    plot.title       = element_text(face = "plain"),
    strip.background = element_rect(fill = NA),
    legend.title     = element_text(size = ttl_pt),
    legend.text      = element_text(size = ttl_pt),
    strip.text       = element_text(size = ttl_pt),
    axis.title       = element_text(size = ttl_pt),
    axis.text        = element_text(size = txt_pt),
    axis.line        = element_blank(),
    panel.border     = element_rect(fill = NA, color = "black", linewidth = ln_pt),
    axis.ticks       = element_line(linewidth = ln_pt, color = "black")
  )

theme_colors <- c(
  "#225ea8",  # blue
  "#e31a1c",  # red
  "#238443",  # green
  "#ec7014",  # orange
  "#8c6bb1",  # purple
  "#737373",  # grey
  "#41b6c4"   # aqua
)

```


