---
title: "Analysis for `r paste0(proj, ': ', seq_date)`"
author: "Benjamin Erickson"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
    toc:            true
    toc_float:      true
    toc_depth:      3
    df_print:       "paged"
    code_folding:   "hide"
    self_contained: true
    theme:          "cosmo"
    highlight:      "tango"

---

```{r "chunk opts", echo=FALSE}

# Set default chunk options
knitr::opts_chunk$set(
  message    = FALSE, 
  warning    = FALSE,
  comment    = "",
  echo       = FALSE,
  dpi        = 150,
  cache      = FALSE,
  cache.lazy = FALSE
)

```

```{r "plotting parameters", include = FALSE}

# Set plotting parameters
# ymls=here::here("samples.yaml")
ymls <- here::here(ymls)
plot_grpss   <- yaml::read_yaml(ymls)
# proj="PNUTS_H66K_CTD_Ser5"
#res_dir="PNUTS_H66K_CTD_Ser5"
# index_map="hg38"
# index_Sample="hg38"
template_dir="workflow/Rmds"

knitr::knit(here::here(template_dir, "setup.Rmd"), "")

```

```{r "png setup", echo=FALSE}
# Summary files
plots_dir <- here::here(res_dir,"heatmap/")

profile_png     <- list.files(path = plots_dir, pattern = "*_profile_plots.png$")
heatmap_png     <- list.files(path = plots_dir, pattern = "*_heatmap.png$")
cluster_png     <- list.files(path = plots_dir, pattern = "*_cluster.png$")
# Check if any plots exist
has_plots <- length(profile_png) > 0 || length(heatmap_png) > 0 || length(cluster_png) > 0
```


```{r load_table, echo=FALSE}
stats_dir <- here(res_dir, "report/")
fq_results     <- str_c(stats_dir, proj, "_results.tsv")
# Read the TSV file into a data frame
my_table <- read_tsv(fq_results)
# Create the table with a smaller font size and wrapped column names
names(my_table) <- gsub("_", "<br>", names(my_table))
my_table %>%
  kbl(escape = FALSE) %>%
  kable_styling(bootstrap_options = c("striped"), full_width = F, position = "left", font_size = 10) %>%
  scroll_box(width = "800px", height = "auto")
```

# Quality Control {.tabset .tabset-pills}

`r knitr::knit_child(here(template_dir, "qc-template.Rmd"), quiet = TRUE)`

```{r conditional-deeptools, results='asis', echo=FALSE}
if(has_plots) {
  cat("# DeepTools Analysis\n\n")
  cat(knitr::knit_child(here(template_dir, "deeptools_plots.Rmd"), quiet = TRUE))
}
```

